import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, collection, addDoc, updateDoc, deleteDoc, doc, onSnapshot, serverTimestamp, setDoc, getDoc } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyAF72PJmHG1G2bzA9sXVNv7Jdw7nywy_h0",authDomain:"belly-276eb.firebaseapp.com",projectId:"belly-276eb",storageBucket:"belly-276eb.firebasestorage.app",messagingSenderId:"99628863972",appId:"1:99628863972:web:d22adec9a7ed782bc237f1"};
const ADMIN_EMAIL="mjh380801@naver.com";const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>`${Number(n||0).toLocaleString("ko-KR")}원`,safe=(v="")=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));let products=[],settings={},cart=JSON.parse(localStorage.getItem("bellyshop_cart")||"[]"),currentUser=null;
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}function saveCart(){localStorage.setItem("bellyshop_cart",JSON.stringify(cart));renderCartCount()}function renderCartCount(){$("#cartCount").textContent=cart.length}
function productCard(p){return `<article class="product-card" data-id="${p.id}">${p.soldout?`<div class="soldout-overlay">품절</div>`:""}${p.featured?`<span class="badge featured">추천</span>`:""}<img src="${safe(p.image)}" alt="${safe(p.name)}" loading="lazy" onerror="this.src='https://placehold.co/800x800?text=BELLYSHOP'"><div class="product-info"><span class="category">${safe(p.category)}</span><h3>${safe(p.name)}</h3><div class="price-row"><span class="price">${money(p.price)}</span>${p.originalPrice?`<span class="original">${money(p.originalPrice)}</span>`:""}</div></div></article>`}
function renderProducts(){const q=$("#searchInput").value.trim().toLowerCase(),category=$("#categoryFilter").value;const visible=products.filter(p=>p.visible!==false).filter(p=>!q||p.name.toLowerCase().includes(q)||(p.description||"").toLowerCase().includes(q)).filter(p=>!category||p.category===category).sort((a,b)=>(b.featured===true)-(a.featured===true)||(b.createdAtMs||0)-(a.createdAtMs||0));$("#productGrid").innerHTML=visible.map(productCard).join("");$("#emptyState").classList.toggle("hidden",visible.length>0);$$('.product-card').forEach(el=>el.addEventListener('click',()=>openProduct(el.dataset.id)));renderCategories()}
function renderCategories(){const cats=[...new Set(products.map(p=>p.category).filter(Boolean))].sort(),selected=$("#categoryFilter").value;$("#categoryFilter").innerHTML='<option value="">전체 카테고리</option>'+cats.map(c=>`<option>${safe(c)}</option>`).join("");$("#categoryFilter").value=cats.includes(selected)?selected:"";$("#categoryList").innerHTML=cats.map(c=>`<option value="${safe(c)}">`).join("")}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const imgs=[p.image,...(p.images||[])].filter(Boolean);$("#productDetail").innerHTML=`<img class="detail-main" id="detailMain" src="${safe(p.image)}" alt="${safe(p.name)}">${imgs.length>1?`<div class="detail-thumbs">${imgs.map(u=>`<img src="${safe(u)}" data-url="${safe(u)}">`).join("")}</div>`:""}<p class="eyebrow">${safe(p.category)}</p><h2>${safe(p.name)}</h2><div class="price-row"><span class="price">${money(p.price)}</span>${p.originalPrice?`<span class="original">${money(p.originalPrice)}</span>`:""}</div><p style="white-space:pre-line;line-height:1.8;color:#555">${safe(p.description)}</p><div class="dialog-actions"><button class="ghost-btn" id="directContactBtn">바로 상담</button><button class="primary-btn" id="addCartBtn" ${p.soldout?"disabled":""}>${p.soldout?"품절":"견적함 담기"}</button></div>`;$$('.detail-thumbs img').forEach(img=>img.onclick=()=>$("#detailMain").src=img.dataset.url);$("#addCartBtn").onclick=()=>{if(!cart.includes(id))cart.push(id);saveCart();toast("견적함에 담았습니다.")};$("#directContactBtn").onclick=()=>contact(`상품 문의\n상품명: ${p.name}\n가격: ${money(p.price)}`);$("#productDialog").showModal()}
function renderCart(){const items=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);$("#cartItems").innerHTML=items.length?items.map(p=>`<div class="cart-row"><img src="${safe(p.image)}"><div><strong>${safe(p.name)}</strong><br><span>${money(p.price)}</span></div><button class="mini-btn delete" data-remove="${p.id}">삭제</button></div>`).join(""):"<p class='empty'>견적함이 비어 있습니다.</p>";$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x!==b.dataset.remove);saveCart();renderCart()})}
function inquiryText(){const items=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);return `BELLYSHOP 상품 상담 요청\n\n${items.map((p,i)=>`${i+1}. ${p.name} / ${money(p.price)}`).join("\n")}\n\n추가 문의:\n${$("#cartMessage").value.trim()}`}
async function copyText(t){try{await navigator.clipboard.writeText(t);toast("문의 내용을 복사했습니다.")}catch{toast("복사하지 못했습니다.")}}function contact(text){copyText(text);if(settings.contactUrl)window.open(settings.contactUrl,"_blank","noopener");else if(settings.phone)location.href=`sms:${settings.phone.replace(/\D/g,"")}?body=${encodeURIComponent(text)}`;else if(settings.email)location.href=`mailto:${settings.email}?subject=${encodeURIComponent("BELLYSHOP 상품 문의")}&body=${encodeURIComponent(text)}`;else toast("관리자가 상담 주소를 아직 설정하지 않았습니다.")}
function renderAdminList(){$("#adminProductList").innerHTML=products.length?products.map(p=>`<div class="admin-item"><img src="${safe(p.image)}"><div><strong>${safe(p.name)}</strong><p>${safe(p.category)} · ${money(p.price)} · ${p.visible!==false?"공개":"비공개"} ${p.soldout?"· 품절":""}</p></div><div class="admin-item-actions"><button class="mini-btn" data-edit="${p.id}">수정</button><button class="mini-btn delete" data-delete="${p.id}">삭제</button></div></div>`).join(""):"<p class='empty'>등록된 상품이 없습니다.</p>";$$('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>removeProduct(b.dataset.delete))}
function resetProductForm(){$("#productForm").reset();$("#productId").value="";$("#pVisible").checked=true;$("#cancelEditBtn").classList.add("hidden")}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$("#productId").value=p.id;$("#pName").value=p.name||"";$("#pCategory").value=p.category||"";$("#pPrice").value=p.price||0;$("#pOriginalPrice").value=p.originalPrice||"";$("#pImage").value=p.image||"";$("#pImages").value=(p.images||[]).join("\n");$("#pDescription").value=p.description||"";$("#pFeatured").checked=!!p.featured;$("#pSoldout").checked=!!p.soldout;$("#pVisible").checked=p.visible!==false;$("#cancelEditBtn").classList.remove("hidden");$("#productForm").scrollIntoView({behavior:"smooth"})}
async function removeProduct(id){if(!confirm("이 상품을 삭제할까요?"))return;try{await deleteDoc(doc(db,"products",id));toast("삭제했습니다.")}catch(e){toast("삭제 실패: "+e.message)}}
async function loadSettings(){const snap=await getDoc(doc(db,"settings","site"));settings=snap.exists()?snap.data():{};$("#heroTitle").innerHTML=safe(settings.heroTitle||"필요한 상품을<br>쉽고 빠르게 상담하세요.").replace(/\n/g,"<br>");$("#heroSubtitle").textContent=settings.heroSubtitle||"상품을 확인하고 견적함에 담은 뒤 상담을 요청할 수 있습니다.";$("#footerText").textContent=settings.footer||"상품 문의는 상담 버튼을 이용해 주세요."}
function fillSettingsForm(){$("#sHeroTitle").value=(settings.heroTitle||"").replace(/<br>/g,"\n");$("#sHeroSubtitle").value=settings.heroSubtitle||"";$("#sContactUrl").value=settings.contactUrl||"";$("#sPhone").value=settings.phone||"";$("#sEmail").value=settings.email||"";$("#sFooter").value=settings.footer||""}
onSnapshot(collection(db,"products"),snap=>{products=snap.docs.map(d=>({id:d.id,...d.data(),createdAtMs:d.data().createdAt?.toMillis?.()||0}));renderProducts();renderAdminList();renderCart()},err=>{console.error(err);toast("상품 데이터를 불러오지 못했습니다.")});loadSettings().catch(console.error);renderCartCount();$("#searchInput").addEventListener("input",renderProducts);$("#categoryFilter").addEventListener("change",renderProducts);$("#cartOpenBtn").onclick=()=>{renderCart();$("#cartDialog").showModal()};$("#adminOpenBtn").onclick=()=>currentUser?$("#adminDialog").showModal():$("#loginDialog").showModal();$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());$("#copyInquiryBtn").onclick=()=>copyText(inquiryText());$("#contactInquiryBtn").onclick=()=>contact(inquiryText());$("#cancelEditBtn").onclick=resetProductForm;
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();$("#loginError").textContent="";const id=$("#adminId").value.trim().toLowerCase();if(id!=="admin"){$("#loginError").textContent="관리자 아이디가 올바르지 않습니다.";return}try{await signInWithEmailAndPassword(auth,ADMIN_EMAIL,$("#adminPassword").value);$("#loginDialog").close();$("#adminPassword").value="";$("#adminDialog").showModal()}catch(e){$("#loginError").textContent="비밀번호가 올바르지 않거나 로그인이 허용되지 않았습니다."}});$("#logoutBtn").onclick=async()=>{await signOut(auth);$("#adminDialog").close();toast("로그아웃했습니다.")};onAuthStateChanged(auth,user=>{currentUser=user?.email===ADMIN_EMAIL?user:null;$("#adminOpenBtn").textContent=currentUser?"상품 관리":"관리자";if(user&&!currentUser)signOut(auth)});
$("#productForm").addEventListener("submit",async e=>{e.preventDefault();const data={name:$("#pName").value.trim(),category:$("#pCategory").value.trim(),price:Number($("#pPrice").value),originalPrice:Number($("#pOriginalPrice").value||0),image:$("#pImage").value.trim(),images:$("#pImages").value.split("\n").map(x=>x.trim()).filter(Boolean),description:$("#pDescription").value.trim(),featured:$("#pFeatured").checked,soldout:$("#pSoldout").checked,visible:$("#pVisible").checked,updatedAt:serverTimestamp()};try{const id=$("#productId").value;if(id)await updateDoc(doc(db,"products",id),data);else await addDoc(collection(db,"products"),{...data,createdAt:serverTimestamp()});resetProductForm();toast(id?"상품을 수정했습니다.":"상품을 등록했습니다.")}catch(e){console.error(e);toast("저장 실패: Firebase 규칙을 확인하세요.")}});
$("#settingsBtn").onclick=()=>{fillSettingsForm();$("#settingsDialog").showModal()};$("#settingsForm").addEventListener("submit",async e=>{e.preventDefault();const data={heroTitle:$("#sHeroTitle").value.trim(),heroSubtitle:$("#sHeroSubtitle").value.trim(),contactUrl:$("#sContactUrl").value.trim(),phone:$("#sPhone").value.trim(),email:$("#sEmail").value.trim(),footer:$("#sFooter").value.trim(),updatedAt:serverTimestamp()};try{await setDoc(doc(db,"settings","site"),data,{merge:true});settings={...settings,...data};await loadSettings();$("#settingsDialog").close();toast("설정을 저장했습니다.")}catch(e){toast("설정 저장에 실패했습니다.")}});
