import {initializeApp} from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import {getFirestore,collection,addDoc,updateDoc,deleteDoc,doc,onSnapshot,serverTimestamp,setDoc,getDoc} from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyAF72PJmHG1G2bzA9sXVNv7Jdw7nywy_h0",authDomain:"belly-276eb.firebaseapp.com",projectId:"belly-276eb",storageBucket:"belly-276eb.firebasestorage.app",messagingSenderId:"99628863972",appId:"1:99628863972:web:d22adec9a7ed782bc237f1"};
const ADMIN_EMAIL="mjh380801@naver.com";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>`${Number(n||0).toLocaleString("ko-KR")}원`;
const safe=(v="")=>String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
let products=[],banners=[],settings={},cart=JSON.parse(localStorage.getItem("bellyshop_cart")||"[]"),currentUser=null,currentView="all",heroIndex=0,heroTimer;

function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2000)}
function saveCart(){localStorage.setItem("bellyshop_cart",JSON.stringify(cart));$("#cartCount").textContent=cart.length}
function badgeHtml(p){return `${p.isNew?'<span class="badge">신상품</span>':""}${p.popular?'<span class="badge popular">인기</span>':""}`}
function card(p){return `<article class="product-card" data-id="${p.id}">${p.soldout?'<div class="soldout-overlay">품절</div>':""}${badgeHtml(p)}<img src="${safe(p.image)}" alt="${safe(p.name)}" loading="lazy" onerror="this.src='https://placehold.co/800x800?text=BELLYSHOP'"><div class="product-info"><span class="category">${safe(p.category)}</span><h3>${safe(p.name)}</h3><span class="price">${money(p.price)}</span>${p.originalPrice?`<span class="original">${money(p.originalPrice)}</span>`:""}</div></article>`}
function attachCards(){ $$(".product-card").forEach(e=>e.onclick=()=>openProduct(e.dataset.id)) }
function render(){
 const q=$("#searchInput").value.trim().toLowerCase(),cat=$("#categoryFilter").value;
 const visible=products.filter(p=>p.visible!==false).filter(p=>!q||p.name.toLowerCase().includes(q)||(p.description||"").toLowerCase().includes(q)).filter(p=>!cat||p.category===cat);
 const newest=visible.filter(p=>p.isNew).slice(0,8),popular=visible.filter(p=>p.popular).slice(0,8),featured=visible.filter(p=>p.featured).slice(0,8);
 $("#newGrid").innerHTML=newest.map(card).join("");$("#popularGrid").innerHTML=popular.map(card).join("");$("#featuredGrid").innerHTML=featured.map(card).join("");
 let all=visible;if(currentView==="new")all=visible.filter(p=>p.isNew);if(currentView==="popular")all=visible.filter(p=>p.popular);if(currentView==="featured")all=visible.filter(p=>p.featured);
 $("#allGrid").innerHTML=all.map(card).join("");$("#emptyState").classList.toggle("hidden",all.length>0);
 $("#newSection").classList.toggle("hidden",currentView!=="all");$("#popularSection").classList.toggle("hidden",currentView!=="all");$("#featuredSection").classList.toggle("hidden",currentView!=="all");
 attachCards();renderCategories();renderAdmin();
}
function renderCategories(){const cs=[...new Set(products.map(p=>p.category).filter(Boolean))].sort(),v=$("#categoryFilter").value;$("#categoryFilter").innerHTML='<option value="">전체 카테고리</option>'+cs.map(c=>`<option>${safe(c)}</option>`).join("");$("#categoryFilter").value=cs.includes(v)?v:"";$("#categoryList").innerHTML=cs.map(c=>`<option value="${safe(c)}">`).join("")}
function setView(v){currentView=v;$$(".tab").forEach(b=>b.classList.toggle("active",b.dataset.view===v));render();$("#allSection").scrollIntoView({behavior:"smooth"});closeMenu()}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const imgs=[p.image,...(p.images||[])].filter(Boolean);$("#productDetail").innerHTML=`<img id="detailMain" class="detail-main" src="${safe(p.image)}">${imgs.length>1?`<div class="detail-thumbs">${imgs.map(u=>`<img src="${safe(u)}" data-u="${safe(u)}">`).join("")}</div>`:""}<p class="admin-kicker">${safe(p.category)}</p><h2>${safe(p.name)}</h2><p><b>${money(p.price)}</b> ${p.originalPrice?`<span class="original">${money(p.originalPrice)}</span>`:""}</p><p style="white-space:pre-line;line-height:1.8;color:#666">${safe(p.description)}</p><div class="dialog-actions"><button id="directBtn" class="light-btn">바로 문의</button><button id="addCartBtn" class="dark-btn" ${p.soldout?"disabled":""}>${p.soldout?"품절":"견적함 담기"}</button></div>`;$$(".detail-thumbs img").forEach(i=>i.onclick=()=>$("#detailMain").src=i.dataset.u);$("#addCartBtn").onclick=()=>{if(!cart.includes(id))cart.push(id);saveCart();toast("견적함에 담았습니다.")};$("#directBtn").onclick=()=>contact(`상품 문의\n상품명: ${p.name}\n가격: ${money(p.price)}`);$("#productDialog").showModal()}
function renderHero(){clearInterval(heroTimer);const list=banners.filter(b=>b.visible!==false);if(!list.length){$("#heroSlider").innerHTML=`<div class="hero-slide active" style="background:linear-gradient(135deg,#333,#aaa)"><div class="hero-content"><p class="mini">BELLYSHOP</p><h1>새로운 컬렉션</h1><p>관리자에서 메인 배너를 등록해 주세요.</p><a class="hero-link" href="#allSection">보러가기</a></div></div>`;$("#heroDots").innerHTML="";return}heroIndex=Math.min(heroIndex,list.length-1);$("#heroSlider").innerHTML=list.map((b,i)=>`<div class="hero-slide ${i===heroIndex?"active":""}" style="background-image:url('${safe(b.image)}')"><div class="hero-content"><p class="mini">${safe(b.eyebrow||"NEW COLLECTION")}</p><h1>${safe(b.title)}</h1><p>${safe(b.subtitle||"")}</p><a class="hero-link" href="${safe(b.link||"#allSection")}">${safe(b.button||"보러가기")}</a></div></div>`).join("");$("#heroDots").innerHTML=list.map((_,i)=>`<button class="hero-dot ${i===heroIndex?"active":""}" data-i="${i}"></button>`).join("");$$(".hero-dot").forEach(d=>d.onclick=()=>{heroIndex=Number(d.dataset.i);renderHero()});if(list.length>1)heroTimer=setInterval(()=>{heroIndex=(heroIndex+1)%list.length;renderHero()},5000)}
function renderCart(){const items=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);$("#cartItems").innerHTML=items.length?items.map(p=>`<div class="cart-row"><img src="${safe(p.image)}"><div><b>${safe(p.name)}</b><br>${money(p.price)}</div><button class="mini-btn delete" data-remove="${p.id}">삭제</button></div>`).join(""):'<div class="empty">견적함이 비어 있습니다.</div>';$$("[data-remove]").forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x!==b.dataset.remove);saveCart();renderCart()})}
function inquiry(){const items=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);return `BELLYSHOP 상품 상담 요청\n\n${items.map((p,i)=>`${i+1}. ${p.name} / ${money(p.price)}`).join("\n")}\n\n추가 문의:\n${$("#cartMessage").value.trim()}`}
async function copy(t){try{await navigator.clipboard.writeText(t);toast("복사했습니다.")}catch{toast("복사하지 못했습니다.")}}
function contact(t){copy(t);if(settings.contactUrl)window.open(settings.contactUrl,"_blank","noopener");else if(settings.phone)location.href=`sms:${settings.phone.replace(/\D/g,"")}?body=${encodeURIComponent(t)}`;else if(settings.email)location.href=`mailto:${settings.email}?subject=BELLYSHOP 문의&body=${encodeURIComponent(t)}`;else toast("관리자에서 상담 주소를 설정해 주세요.")}
function renderAdmin(){ $("#adminProductList").innerHTML=products.length?products.map(p=>`<div class="admin-item"><img src="${safe(p.image)}"><div><b>${safe(p.name)}</b><p>${safe(p.category)} · ${money(p.price)} · ${p.visible!==false?"공개":"비공개"}</p></div><div class="admin-actions"><button class="mini-btn" data-edit="${p.id}">수정</button><button class="mini-btn delete" data-del="${p.id}">삭제</button></div></div>`).join(""):'<div class="empty">등록된 상품이 없습니다.</div>';$$("[data-edit]").forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));$$("[data-del]").forEach(b=>b.onclick=()=>removeProduct(b.dataset.del))}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$("#productId").value=id;$("#pName").value=p.name||"";$("#pCategory").value=p.category||"";$("#pPrice").value=p.price||0;$("#pOriginalPrice").value=p.originalPrice||"";$("#pImage").value=p.image||"";$("#pImages").value=(p.images||[]).join("\n");$("#pDescription").value=p.description||"";$("#pNew").checked=!!p.isNew;$("#pPopular").checked=!!p.popular;$("#pFeatured").checked=!!p.featured;$("#pSoldout").checked=!!p.soldout;$("#pVisible").checked=p.visible!==false;$("#cancelEditBtn").classList.remove("hidden");$("#productForm").scrollIntoView({behavior:"smooth"})}
function resetProduct(){ $("#productForm").reset();$("#productId").value="";$("#pNew").checked=true;$("#pVisible").checked=true;$("#cancelEditBtn").classList.add("hidden")}
async function removeProduct(id){if(confirm("이 상품을 삭제할까요?"))try{await deleteDoc(doc(db,"products",id));toast("삭제했습니다.")}catch(e){toast("삭제 실패")}}
function renderBannerList(){ $("#bannerList").innerHTML=banners.length?banners.map(b=>`<div class="admin-item"><img src="${safe(b.image)}"><div><b>${safe(b.title)}</b><p>${b.visible!==false?"공개":"비공개"}</p></div><div class="admin-actions"><button class="mini-btn" data-bedit="${b.id}">수정</button><button class="mini-btn delete" data-bdel="${b.id}">삭제</button></div></div>`).join(""):'<div class="empty">등록된 배너가 없습니다.</div>';$$("[data-bedit]").forEach(b=>b.onclick=()=>editBanner(b.dataset.bedit));$$("[data-bdel]").forEach(b=>b.onclick=async()=>{if(confirm("배너를 삭제할까요?"))await deleteDoc(doc(db,"banners",b.dataset.bdel))})}
function editBanner(id){const b=banners.find(x=>x.id===id);$("#bannerId").value=id;$("#bEyebrow").value=b.eyebrow||"";$("#bTitle").value=b.title||"";$("#bSubtitle").value=b.subtitle||"";$("#bImage").value=b.image||"";$("#bButton").value=b.button||"";$("#bLink").value=b.link||"";$("#bVisible").checked=b.visible!==false;$("#cancelBannerEditBtn").classList.remove("hidden")}
function resetBanner(){ $("#bannerForm").reset();$("#bannerId").value="";$("#bVisible").checked=true;$("#bButton").value="보러가기";$("#cancelBannerEditBtn").classList.add("hidden")}
function openMenu(){$("#sideMenu").classList.add("open");$("#overlay").classList.remove("hidden")}function closeMenu(){$("#sideMenu").classList.remove("open");$("#overlay").classList.add("hidden")}

onSnapshot(collection(db,"products"),s=>{products=s.docs.map(d=>({id:d.id,...d.data()}));render();renderCart()},e=>toast("상품 데이터를 불러오지 못했습니다."));
onSnapshot(collection(db,"banners"),s=>{banners=s.docs.map(d=>({id:d.id,...d.data()}));renderHero();renderBannerList()});
getDoc(doc(db,"settings","site")).then(s=>{settings=s.exists()?s.data():{};$("#footerBrand").textContent=settings.brand||"BELLYSHOP";$("#footerText").textContent=settings.footer||"상품 상담은 카카오톡 문의를 이용해 주세요."});

$("#menuBtn").onclick=openMenu;$("#menuCloseBtn").onclick=closeMenu;$("#overlay").onclick=closeMenu;$("#searchToggleBtn").onclick=()=>$("#searchBar").classList.toggle("hidden");$("#searchInput").oninput=render;$("#categoryFilter").onchange=render;
$$("[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));
$("#adminOpenBtn").onclick=$("#sideAdminBtn").onclick=()=>currentUser?$("#adminDialog").showModal():$("#loginDialog").showModal();
$("#cartOpenBtn").onclick=()=>{renderCart();$("#cartDialog").showModal()};$("#talkBtn").onclick=()=>contact("BELLYSHOP 상품 상담을 요청합니다.");$("#shareBtn").onclick=()=>navigator.share?navigator.share({title:"BELLYSHOP",url:location.href}):copy(location.href);$("#copyInquiryBtn").onclick=()=>copy(inquiry());$("#contactInquiryBtn").onclick=()=>contact(inquiry());
$$("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());$("#cancelEditBtn").onclick=resetProduct;$("#cancelBannerEditBtn").onclick=resetBanner;
$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent="";if($("#adminId").value.trim().toLowerCase()!=="admin"){ $("#loginError").textContent="아이디가 올바르지 않습니다.";return}try{await signInWithEmailAndPassword(auth,ADMIN_EMAIL,$("#adminPassword").value);$("#loginDialog").close();$("#adminDialog").showModal()}catch{$("#loginError").textContent="비밀번호가 올바르지 않습니다."}};
onAuthStateChanged(auth,u=>{currentUser=u?.email===ADMIN_EMAIL?u:null;$("#adminOpenBtn").textContent=currentUser?"상품 관리":"관리자";if(u&&!currentUser)signOut(auth)});
$("#logoutBtn").onclick=async()=>{await signOut(auth);$("#adminDialog").close();toast("로그아웃했습니다.")};
$("#productForm").onsubmit=async e=>{e.preventDefault();const data={name:$("#pName").value.trim(),category:$("#pCategory").value.trim(),price:Number($("#pPrice").value),originalPrice:Number($("#pOriginalPrice").value||0),image:$("#pImage").value.trim(),images:$("#pImages").value.split("\n").map(x=>x.trim()).filter(Boolean),description:$("#pDescription").value.trim(),isNew:$("#pNew").checked,popular:$("#pPopular").checked,featured:$("#pFeatured").checked,soldout:$("#pSoldout").checked,visible:$("#pVisible").checked,updatedAt:serverTimestamp()};try{const id=$("#productId").value;if(id)await updateDoc(doc(db,"products",id),data);else await addDoc(collection(db,"products"),{...data,createdAt:serverTimestamp()});resetProduct();toast("저장했습니다.")}catch(e){toast("저장 실패: Firestore 규칙을 확인하세요.")}};
$("#bannerBtn").onclick=()=>$("#bannerDialog").showModal();$("#bannerForm").onsubmit=async e=>{e.preventDefault();const data={eyebrow:$("#bEyebrow").value.trim(),title:$("#bTitle").value.trim(),subtitle:$("#bSubtitle").value.trim(),image:$("#bImage").value.trim(),button:$("#bButton").value.trim(),link:$("#bLink").value.trim(),visible:$("#bVisible").checked,updatedAt:serverTimestamp()};const id=$("#bannerId").value;if(id)await updateDoc(doc(db,"banners",id),data);else await addDoc(collection(db,"banners"),{...data,createdAt:serverTimestamp()});resetBanner();toast("배너를 저장했습니다.")};
$("#settingsBtn").onclick=()=>{$("#sBrand").value=settings.brand||"BELLYSHOP";$("#sContactUrl").value=settings.contactUrl||"";$("#sPhone").value=settings.phone||"";$("#sEmail").value=settings.email||"";$("#sFooter").value=settings.footer||"";$("#settingsDialog").showModal()};
$("#settingsForm").onsubmit=async e=>{e.preventDefault();const data={brand:$("#sBrand").value.trim(),contactUrl:$("#sContactUrl").value.trim(),phone:$("#sPhone").value.trim(),email:$("#sEmail").value.trim(),footer:$("#sFooter").value.trim(),updatedAt:serverTimestamp()};await setDoc(doc(db,"settings","site"),data,{merge:true});settings={...settings,...data};$("#footerBrand").textContent=settings.brand||"BELLYSHOP";$("#footerText").textContent=settings.footer||"";$("#settingsDialog").close();toast("설정을 저장했습니다.")};
saveCart();